// Builds src/design-system/icons.generated.ts from the Open Circuit SVG pack (single source of truth).
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, '..', '..', 'design-source', 'icons');
const entries = readdirSync(dir).filter((f) => f.endsWith('.svg')).sort().map((file) => {
  const svg = readFileSync(join(dir, file), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  return [file.replace('.svg', ''), inner];
});
const body = entries.map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`).join('\n');
writeFileSync(join(root, 'src', 'design-system', 'icons.generated.ts'),
  `// GENERATED by scripts/generate-icons.mjs — do not edit. Source: design-source/icons/*.svg\nexport const iconPaths = {\n${body}\n} as const;\n\nexport type TechIconName = keyof typeof iconPaths;\n`);
console.log(`generated ${entries.length} icons`);
